/**
 * Core flight & trajectory domain model.
 *
 * These types are the internal representation the rest of the system depends
 * on. Nothing outside `src/data` should ever see a raw OpenSky, Google
 * Contrails, or Contrails.org response shape — everything gets normalized
 * into these types first. See src/data/providers for the adapters.
 */

export type AircraftClass =
  | "narrowbody" // e.g. A320 family, 737 family
  | "widebody" // e.g. 787, A350, 777
  | "regional";

export interface AircraftModel {
  /** ICAO type designator, e.g. "B789", "A20N". Informational only. */
  icaoType: string;
  /** Human-readable name, e.g. "Boeing 787-9". */
  displayName: string;
  aircraftClass: AircraftClass;
  /** Typical operating empty + payload reference mass, kg. Approximate. */
  referenceMassKg: number;
  /** Typical long-haul cruise mass fraction used for our simplified fuel model. */
  typicalCruiseMassKg: number;
  /** Typical cruise true airspeed, knots. Approximate, not type-certified data. */
  typicalCruiseTasKts: number;
  source: "openap" | "public-documentation";
}

export interface TrajectoryPoint {
  /** ISO-8601 UTC timestamp. */
  timestamp: string;
  latitude: number;
  longitude: number;
  /** Altitude in feet. */
  altitudeFt: number;
  /** Ground speed in knots, if known. */
  groundSpeedKts?: number;
  /** True heading in degrees [0, 360). */
  heading?: number;
  /**
   * Original observation resolution in seconds (the gap to the *next* raw
   * observation this point came from, before any visualization interpolation
   * was applied). Undefined for points that are themselves interpolated.
   * Used so scientific calculations can tell real observations from
   * visualization-only interpolation - see src/science/trajectory.ts.
   */
  sourceResolutionSec?: number;
  /** True if this point was generated by interpolation, not observed. */
  interpolated: boolean;
}

export interface Flight {
  id: string;
  callsign: string;
  origin: string; // IATA code
  destination: string; // IATA code
  departureTime: string; // ISO-8601 UTC
  arrivalTime: string; // ISO-8601 UTC
  aircraft: AircraftModel;
  trajectory: TrajectoryPoint[];
  /**
   * Where the trajectory came from. Never claim live/raw telemetry unless it
   * actually is; the demo dataset is explicit about being a reconstructed,
   * representative trajectory - see demo-data/README.md.
   */
  dataProvenance: {
    source: "opensky-historical" | "opensky-live" | "reconstructed-representative";
    note: string;
  };
}

/**
 * Atmospheric + contrail-relevant conditions sampled at one trajectory point.
 * Field names deliberately mirror the Contrails.org / pycontrails CoCiP
 * trajectory API vocabulary (sac, issr, energy_forcing per segment) so the
 * internal model can be swapped to live data with the same shape:
 * https://apidocs.contrails.org/notebooks/research_api.html
 */
export interface AtmosphericSample {
  timestamp: string;
  latitude: number;
  longitude: number;
  /** Nearest available flight level (hundreds of feet), matching provider grid resolution. */
  flightLevel: number;
  /** Ambient temperature, Kelvin. */
  temperatureK: number;
  /** Relative humidity over ice, percent (100 = ice-saturated). */
  relativeHumidityIcePct: number;
  /** Schmidt-Appleman Criterion: contrail forms if engine plume can reach saturation. */
  sac: 0 | 1 | null;
  /** Ice-supersaturated region indicator. */
  issr: 0 | 1 | null;
  /** Whether a contrail forming at this waypoint is predicted to persist. */
  persistentContrailProbability: number | null;
  /**
   * CoCiP-modeled energy forcing contribution of the segment starting at this
   * waypoint, in Joules. Positive = net warming, negative = net cooling
   * (roughly 35% of persistent contrails are net-cooling per CoCiP climatology:
   * https://apidocs.contrails.org/ef-interpretation.html). Null if SAC/ISSR
   * conditions mean no persistent contrail is predicted, or data is unavailable.
   */
  segmentEnergyForcingJ: number | null;
  confidence: "low" | "medium" | "high";
  /** Which provider produced this sample. */
  providerId: "google-contrails" | "contrails-org-cocip" | "demo-dataset";
}

export interface AnnotatedTrajectoryPoint {
  point: TrajectoryPoint;
  sample: AtmosphericSample | null;
}
